[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/neco-syntax'

[[plugins]]
repo = 'Shougo/neco-vim'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'davidhalter/jedi-vim'

[[plugins]]
repo = 'kannokanno/previm'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'mattn/sonictemplate-vim'

[[plugins]]
repo = 'tpope/vim-markdown'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'ujihisa/neco-look'

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'lervag/vimtex'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'Shougo/deol.nvim'

[[plugins]]
repo = 'jistr/vim-nerdtree-tabs'

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'ervandew/supertab'

[[plugins]]
repo = 'valloric/matchtagalways'

[[plugins]]
repo = 'maxmellon/vim-jsx-pretty'

[[plugins]]
repo = 'HerringtonDarkholme/yats.vim'

[[plugins]]
repo = 'tell-k/vim-autopep8'
